name: Deploy Azure VM from GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Only create resource group if it does NOT already exist
      - name: Check if resource group exists
        id: check_rg
        run: |
          if az group show --name github-rg &> /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create resource group (only if missing)
        if: steps.check_rg.outputs.exists == 'false'
        run: |
          az group create --name github-rg --location eastus

      - name: Create virtual machine
        run: |
          az vm create \
            --resource-group github-rg \
            --name github-vm \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --size Standard_B1s \
            --generate-ssh-keys
