# I am just adding it for debugging issue
name: Deploy Azure VM from GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  deploy-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: |
          az group create --name github-rg --location centralus

      - name: Create virtual machine
        run: |
          az vm create \
            --resource-group github-rg \
            --name github-vm \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --size Standard_B1s \
            --generate-ssh-keys
